---
- name: Install Apache2
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2 Package
      apt:
        name: apache2
        state: present

    - name: Enable and Start Apache2 Service
      service:
        name: apache2
        state: started
        enabled: yes
