name: Create Image for Image Updates

on:
  workflow_dispatch:
  push:
    branches:
      - demoworkflow2
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: check_branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          script: |
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'demoworkflow2'
              });
              core.setOutput("exists", "true");
            } catch (error) {
              if (error.status === 404) {
                core.setOutput("exists", "false");
                console.log("❌ No branch named demoworkflow2");
              } else {
                throw error;
              }
            }

      - name: Output if branch does not exist
        if: steps.check_branch.outputs.exists == 'false'
        run: echo "❌ No branch named demoworkflow2"

      - name: Checkout
        if: steps.check_branch.outputs.exists == 'true'
        uses: actions/checkout@v2
        with:
          ref: demoworkflow2

      - name: Check for Existing Pull Request
        if: steps.check_branch.outputs.exists == 'true'
        id: check_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'demoworkflow2',
              state: 'open'
            });
            const prUrl = pullRequests.length > 0 ? pullRequests[0].html_url : '';
            core.setOutput('existing_pr_url', prUrl);

      - name: Create Pull Request
        if: steps.check_branch.outputs.exists == 'true' && steps.check_pr.outputs.existing_pr_url == ''
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          script: |
            const date = new Date().toISOString().split('T')[0];
            const title = `Flux Image Update (${date})`;
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: 'demoworkflow2',
              base: 'demoworkflow',
              body: 'This is an automated pull request created by GitHub Actions.',
            });
            core.setOutput('pr_url', pullRequest.html_url);

      - name: Output Pull Request URL
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          if [ "${{ steps.check_pr.outputs.existing_pr_url }}" != "" ]; then
            echo "✅ Pull Request already exists: ${{ steps.check_pr.outputs.existing_pr_url }}"
          else
            echo "✅ Created new Pull Request: ${{ steps.create_pr.outputs.pr_url }}"
          fi
