name: Create Image for Image Updates

on:
  workflow_dispatch:
  push:
    branches:
      - feature/image-update-flux

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: check_branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'feature/image-update-flux'
              });
              core.setOutput("exists", "true");
            } catch (error) {
              if (error.status === 404) {
                core.setOutput("exists", "false");
                console.log("No branch named feature/image-update-flux");
              } else {
                throw error;
              }
            }

      - name: Output if branch does not exist
        if: steps.check_branch.outputs.exists == 'false'
        run: echo "❌ No branch named feature/image-update-flux"

      - name: Checkout
        if: steps.check_branch.outputs.exists == 'true'
        uses: actions/checkout@v2
        with:
          ref: feature/image-update-flux

      - name: Check for Existing Pull Request
        if: steps.check_branch.outputs.exists == 'true'
        id: check_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'feature/image-update-flux',
              state: 'open'
            });
            const prUrl = pullRequests.length > 0 ? pullRequests[0].html_url : '';
            core.setOutput('result', prUrl);

      - name: Create Pull Request
        if: steps.check_branch.outputs.exists == 'true' && steps.check_pr.outputs.result == ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const date = new Date().toISOString().split('T')[0];
            const title = `Flux Image Update (${date})`;
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: 'feature/image-update-flux',
              base: 'master',
              body: 'This is an automated pull request created by GitHub Actions.',
            });
            core.setOutput('pull-request-url', pullRequest.html_url);

      - name: Output Existing Pull Request URL
        if: steps.check_branch.outputs.exists == 'true' && steps.check_pr.outputs.result != ''
        run: |
          echo "✅ Pull Request already exists: ${{ steps.check_pr.outputs.result }}"
